namespace DevExpress.UITemplates.Collection.UserControls {
    partial class UC_ThemKH {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if(disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UC_ThemKH));
            this.dataLayout = new DevExpress.XtraDataLayout.DataLayoutControl();
            this.barManager = new DevExpress.XtraBars.BarManager(this.components);
            this.actionsBar = new DevExpress.XtraBars.Bar();
            this.btn_Add = new DevExpress.XtraBars.BarButtonItem();
            this.btn_Clear = new DevExpress.XtraBars.BarButtonItem();
            this.btn_Reset = new DevExpress.XtraBars.BarButtonItem();
            this.btn_Thoat = new DevExpress.XtraBars.BarButtonItem();
            this.barDockControlTop = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlBottom = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlLeft = new DevExpress.XtraBars.BarDockControl();
            this.barDockControlRight = new DevExpress.XtraBars.BarDockControl();
            this.actionImages = new DevExpress.Utils.SvgImageCollection(this.components);
            this.txtMaKH = new DevExpress.XtraEditors.TextEdit();
            this.txtDiaChi = new DevExpress.XtraEditors.TextEdit();
            this.txtTenKH = new DevExpress.XtraEditors.TextEdit();
            this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
            this.Item_MaKH = new DevExpress.XtraLayout.LayoutControlItem();
            this.emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.ItemForAddress = new DevExpress.XtraLayout.LayoutControlItem();
            this.emptySpaceItem2 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.emptySpaceItem5 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.emptySpaceItem4 = new DevExpress.XtraLayout.EmptySpaceItem();
            this.Item_DiaChi = new DevExpress.XtraLayout.LayoutControlItem();
            this.txtTenKH1 = new DevExpress.XtraEditors.TextEdit();
            this.ItemForAddress1 = new DevExpress.XtraLayout.LayoutControlItem();
            this.txtTenKH2 = new DevExpress.XtraEditors.TextEdit();
            this.ItemForAddress2 = new DevExpress.XtraLayout.LayoutControlItem();
            this.txtSdt = new DevExpress.XtraEditors.TextEdit();
            this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
            ((System.ComponentModel.ISupportInitialize)(this.dataLayout)).BeginInit();
            this.dataLayout.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.barManager)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.actionImages)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtMaKH.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtDiaChi.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTenKH.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Item_MaKH)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForAddress)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Item_DiaChi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTenKH1.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForAddress1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTenKH2.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForAddress2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtSdt.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
            this.SuspendLayout();
            // 
            // dataLayout
            // 
            this.dataLayout.AllowCustomization = false;
            this.dataLayout.AllowGeneratingCollectionProperties = DevExpress.Utils.DefaultBoolean.True;
            this.dataLayout.AllowGeneratingNestedGroups = DevExpress.Utils.DefaultBoolean.True;
            this.dataLayout.Controls.Add(this.txtMaKH);
            this.dataLayout.Controls.Add(this.txtDiaChi);
            this.dataLayout.Controls.Add(this.txtSdt);
            this.dataLayout.Controls.Add(this.txtTenKH);
            this.dataLayout.Controls.Add(this.txtTenKH1);
            this.dataLayout.Controls.Add(this.txtTenKH2);
            this.dataLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataLayout.Location = new System.Drawing.Point(0, 34);
            this.dataLayout.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.dataLayout.Name = "dataLayout";
            this.dataLayout.OptionsView.UseParentAutoScaleFactor = true;
            this.dataLayout.Root = this.layoutControlGroup1;
            this.dataLayout.Size = new System.Drawing.Size(750, 580);
            this.dataLayout.TabIndex = 0;
            // 
            // barManager
            // 
            this.barManager.Bars.AddRange(new DevExpress.XtraBars.Bar[] {
            this.actionsBar});
            this.barManager.DockControls.Add(this.barDockControlTop);
            this.barManager.DockControls.Add(this.barDockControlBottom);
            this.barManager.DockControls.Add(this.barDockControlLeft);
            this.barManager.DockControls.Add(this.barDockControlRight);
            this.barManager.Form = this;
            this.barManager.Images = this.actionImages;
            this.barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] {
            this.btn_Add,
            this.btn_Clear,
            this.btn_Reset,
            this.btn_Thoat});
            this.barManager.MainMenu = this.actionsBar;
            this.barManager.MaxItemId = 4;
            // 
            // actionsBar
            // 
            this.actionsBar.BarName = "Actions";
            this.actionsBar.DockCol = 0;
            this.actionsBar.DockRow = 0;
            this.actionsBar.DockStyle = DevExpress.XtraBars.BarDockStyle.Top;
            this.actionsBar.LinksPersistInfo.AddRange(new DevExpress.XtraBars.LinkPersistInfo[] {
            new DevExpress.XtraBars.LinkPersistInfo(this.btn_Add),
            new DevExpress.XtraBars.LinkPersistInfo(this.btn_Clear),
            new DevExpress.XtraBars.LinkPersistInfo(this.btn_Thoat)});
            this.actionsBar.OptionsBar.AllowQuickCustomization = false;
            this.actionsBar.OptionsBar.DisableCustomization = true;
            this.actionsBar.OptionsBar.DrawDragBorder = false;
            this.actionsBar.OptionsBar.MultiLine = true;
            this.actionsBar.OptionsBar.UseWholeRow = true;
            this.actionsBar.Text = "Actions";
            // 
            // btn_Add
            // 
            this.btn_Add.Caption = "Lưu";
            this.btn_Add.Id = 0;
            this.btn_Add.ImageOptions.ImageIndex = 0;
            this.btn_Add.Name = "btn_Add";
            this.btn_Add.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph;
            this.btn_Add.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btn_Add_ItemClick);
            // 
            // btn_Clear
            // 
            this.btn_Clear.Caption = "Làm mới";
            this.btn_Clear.Id = 1;
            this.btn_Clear.ImageOptions.ImageIndex = 2;
            this.btn_Clear.Name = "btn_Clear";
            this.btn_Clear.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph;
            this.btn_Clear.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btn_Clear_ItemClick);
            // 
            // btn_Reset
            // 
            this.btn_Reset.Caption = "Đặt lại";
            this.btn_Reset.Id = 2;
            this.btn_Reset.ImageOptions.ImageIndex = 1;
            this.btn_Reset.Name = "btn_Reset";
            this.btn_Reset.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph;
            // 
            // btn_Thoat
            // 
            this.btn_Thoat.Caption = "Thoát";
            this.btn_Thoat.Id = 3;
            this.btn_Thoat.ImageOptions.Image = ((System.Drawing.Image)(resources.GetObject("btn_Thoat.ImageOptions.Image")));
            this.btn_Thoat.ImageOptions.LargeImage = ((System.Drawing.Image)(resources.GetObject("btn_Thoat.ImageOptions.LargeImage")));
            this.btn_Thoat.Name = "btn_Thoat";
            this.btn_Thoat.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph;
            this.btn_Thoat.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btn_Thoat_ItemClick);
            // 
            // barDockControlTop
            // 
            this.barDockControlTop.CausesValidation = false;
            this.barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.barDockControlTop.Location = new System.Drawing.Point(0, 0);
            this.barDockControlTop.Manager = this.barManager;
            this.barDockControlTop.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.barDockControlTop.Size = new System.Drawing.Size(750, 34);
            // 
            // barDockControlBottom
            // 
            this.barDockControlBottom.CausesValidation = false;
            this.barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.barDockControlBottom.Location = new System.Drawing.Point(0, 614);
            this.barDockControlBottom.Manager = this.barManager;
            this.barDockControlBottom.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.barDockControlBottom.Size = new System.Drawing.Size(750, 0);
            // 
            // barDockControlLeft
            // 
            this.barDockControlLeft.CausesValidation = false;
            this.barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.barDockControlLeft.Location = new System.Drawing.Point(0, 34);
            this.barDockControlLeft.Manager = this.barManager;
            this.barDockControlLeft.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.barDockControlLeft.Size = new System.Drawing.Size(0, 580);
            // 
            // barDockControlRight
            // 
            this.barDockControlRight.CausesValidation = false;
            this.barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right;
            this.barDockControlRight.Location = new System.Drawing.Point(750, 34);
            this.barDockControlRight.Manager = this.barManager;
            this.barDockControlRight.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.barDockControlRight.Size = new System.Drawing.Size(0, 580);
            // 
            // actionImages
            // 
            this.actionImages.Add("save", "image://svgimages/save/save.svg");
            this.actionImages.Add("refresh", "image://svgimages/icon builder/actions_refresh.svg");
            this.actionImages.Add("clearall", "image://svgimages/spreadsheet/clearall.svg");
            // 
            // txtMaKH
            // 
            this.txtMaKH.Enabled = false;
            this.txtMaKH.EnterMoveNextControl = true;
            this.txtMaKH.Location = new System.Drawing.Point(144, 14);
            this.txtMaKH.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtMaKH.Name = "txtMaKH";
            this.txtMaKH.Properties.ValidateOnEnterKey = true;
            this.txtMaKH.Size = new System.Drawing.Size(590, 26);
            this.txtMaKH.StyleController = this.dataLayout;
            this.txtMaKH.TabIndex = 8;
            // 
            // txtDiaChi
            // 
            this.txtDiaChi.EnterMoveNextControl = true;
            this.txtDiaChi.Location = new System.Drawing.Point(144, 188);
            this.txtDiaChi.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtDiaChi.Name = "txtDiaChi";
            this.txtDiaChi.Properties.ValidateOnEnterKey = true;
            this.txtDiaChi.Size = new System.Drawing.Size(590, 26);
            this.txtDiaChi.StyleController = this.dataLayout;
            this.txtDiaChi.TabIndex = 9;
            // 
            // txtTenKH
            // 
            this.txtTenKH.EnterMoveNextControl = true;
            this.txtTenKH.Location = new System.Drawing.Point(144, 72);
            this.txtTenKH.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtTenKH.Name = "txtTenKH";
            this.txtTenKH.Size = new System.Drawing.Size(590, 26);
            this.txtTenKH.StyleController = this.dataLayout;
            this.txtTenKH.TabIndex = 19;
            this.txtTenKH.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.text_TenKH_KeyPress);
            // 
            // layoutControlGroup1
            // 
            this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
            this.layoutControlGroup1.GroupBordersVisible = false;
            this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGeneratedGroup0,
            this.ItemForAddress1,
            this.ItemForAddress2});
            this.layoutControlGroup1.Name = "Root";
            this.layoutControlGroup1.Size = new System.Drawing.Size(750, 580);
            this.layoutControlGroup1.TextVisible = false;
            // 
            // autoGeneratedGroup0
            // 
            this.autoGeneratedGroup0.AllowDrawBackground = false;
            this.autoGeneratedGroup0.CustomizationFormText = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.GroupBordersVisible = false;
            this.autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.Item_MaKH,
            this.emptySpaceItem1,
            this.ItemForAddress,
            this.emptySpaceItem2,
            this.emptySpaceItem5,
            this.emptySpaceItem4,
            this.Item_DiaChi,
            this.layoutControlItem1});
            this.autoGeneratedGroup0.Location = new System.Drawing.Point(0, 0);
            this.autoGeneratedGroup0.Name = "autoGeneratedGroup0";
            this.autoGeneratedGroup0.Size = new System.Drawing.Size(724, 496);
            // 
            // Item_MaKH
            // 
            this.Item_MaKH.Control = this.txtMaKH;
            this.Item_MaKH.CustomizationFormText = "First Name";
            this.Item_MaKH.Location = new System.Drawing.Point(0, 0);
            this.Item_MaKH.Name = "Item_MaKH";
            this.Item_MaKH.Size = new System.Drawing.Size(724, 30);
            this.Item_MaKH.Text = "Mã khách hàng";
            this.Item_MaKH.TextSize = new System.Drawing.Size(113, 19);
            // 
            // emptySpaceItem1
            // 
            this.emptySpaceItem1.AllowHotTrack = false;
            this.emptySpaceItem1.CustomizationFormText = "emptySpaceItem1";
            this.emptySpaceItem1.Location = new System.Drawing.Point(0, 30);
            this.emptySpaceItem1.MaxSize = new System.Drawing.Size(0, 28);
            this.emptySpaceItem1.MinSize = new System.Drawing.Size(15, 28);
            this.emptySpaceItem1.Name = "emptySpaceItem1";
            this.emptySpaceItem1.Size = new System.Drawing.Size(724, 28);
            this.emptySpaceItem1.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.emptySpaceItem1.TextSize = new System.Drawing.Size(0, 0);
            // 
            // ItemForAddress
            // 
            this.ItemForAddress.Control = this.txtTenKH;
            this.ItemForAddress.CustomizationFormText = "Address";
            this.ItemForAddress.Location = new System.Drawing.Point(0, 58);
            this.ItemForAddress.Name = "ItemForAddress";
            this.ItemForAddress.Size = new System.Drawing.Size(724, 30);
            this.ItemForAddress.Text = "Tên khách hàng";
            this.ItemForAddress.TextSize = new System.Drawing.Size(113, 19);
            // 
            // emptySpaceItem2
            // 
            this.emptySpaceItem2.AllowHotTrack = false;
            this.emptySpaceItem2.CustomizationFormText = "emptySpaceItem2";
            this.emptySpaceItem2.Location = new System.Drawing.Point(0, 88);
            this.emptySpaceItem2.MaxSize = new System.Drawing.Size(0, 28);
            this.emptySpaceItem2.MinSize = new System.Drawing.Size(15, 28);
            this.emptySpaceItem2.Name = "emptySpaceItem2";
            this.emptySpaceItem2.Size = new System.Drawing.Size(724, 28);
            this.emptySpaceItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.emptySpaceItem2.TextSize = new System.Drawing.Size(0, 0);
            // 
            // emptySpaceItem5
            // 
            this.emptySpaceItem5.AllowHotTrack = false;
            this.emptySpaceItem5.CustomizationFormText = "emptySpaceItem5";
            this.emptySpaceItem5.Location = new System.Drawing.Point(0, 146);
            this.emptySpaceItem5.MaxSize = new System.Drawing.Size(0, 28);
            this.emptySpaceItem5.MinSize = new System.Drawing.Size(15, 28);
            this.emptySpaceItem5.Name = "emptySpaceItem5";
            this.emptySpaceItem5.Size = new System.Drawing.Size(724, 28);
            this.emptySpaceItem5.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.emptySpaceItem5.TextSize = new System.Drawing.Size(0, 0);
            // 
            // emptySpaceItem4
            // 
            this.emptySpaceItem4.AllowHotTrack = false;
            this.emptySpaceItem4.CustomizationFormText = "emptySpaceItem4";
            this.emptySpaceItem4.Location = new System.Drawing.Point(0, 204);
            this.emptySpaceItem4.MaxSize = new System.Drawing.Size(30, 0);
            this.emptySpaceItem4.MinSize = new System.Drawing.Size(30, 15);
            this.emptySpaceItem4.Name = "emptySpaceItem4";
            this.emptySpaceItem4.Size = new System.Drawing.Size(724, 292);
            this.emptySpaceItem4.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
            this.emptySpaceItem4.TextSize = new System.Drawing.Size(0, 0);
            // 
            // Item_DiaChi
            // 
            this.Item_DiaChi.Control = this.txtDiaChi;
            this.Item_DiaChi.CustomizationFormText = "Last Name";
            this.Item_DiaChi.Location = new System.Drawing.Point(0, 174);
            this.Item_DiaChi.Name = "Item_DiaChi";
            this.Item_DiaChi.Size = new System.Drawing.Size(724, 30);
            this.Item_DiaChi.Text = "Địa chỉ";
            this.Item_DiaChi.TextSize = new System.Drawing.Size(113, 19);
            // 
            // txtTenKH1
            // 
            this.txtTenKH1.EnterMoveNextControl = true;
            this.txtTenKH1.Location = new System.Drawing.Point(145, 510);
            this.txtTenKH1.Margin = new System.Windows.Forms.Padding(4);
            this.txtTenKH1.Name = "txtTenKH1";
            this.txtTenKH1.Size = new System.Drawing.Size(588, 26);
            this.txtTenKH1.StyleController = this.dataLayout;
            this.txtTenKH1.TabIndex = 19;
            // 
            // ItemForAddress1
            // 
            this.ItemForAddress1.Control = this.txtTenKH1;
            this.ItemForAddress1.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForAddress1.CustomizationFormText = "Address";
            this.ItemForAddress1.Location = new System.Drawing.Point(0, 496);
            this.ItemForAddress1.Name = "ItemForAddress1";
            this.ItemForAddress1.Padding = new DevExpress.XtraLayout.Utils.Padding(4, 4, 2, 2);
            this.ItemForAddress1.Size = new System.Drawing.Size(724, 30);
            this.ItemForAddress1.Text = "Tên khách hàng";
            this.ItemForAddress1.TextSize = new System.Drawing.Size(113, 19);
            // 
            // txtTenKH2
            // 
            this.txtTenKH2.EnterMoveNextControl = true;
            this.txtTenKH2.Location = new System.Drawing.Point(145, 540);
            this.txtTenKH2.Margin = new System.Windows.Forms.Padding(4);
            this.txtTenKH2.Name = "txtTenKH2";
            this.txtTenKH2.Size = new System.Drawing.Size(588, 26);
            this.txtTenKH2.StyleController = this.dataLayout;
            this.txtTenKH2.TabIndex = 19;
            // 
            // ItemForAddress2
            // 
            this.ItemForAddress2.Control = this.txtTenKH2;
            this.ItemForAddress2.ControlAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.ItemForAddress2.CustomizationFormText = "Address";
            this.ItemForAddress2.Location = new System.Drawing.Point(0, 526);
            this.ItemForAddress2.Name = "ItemForAddress2";
            this.ItemForAddress2.Padding = new DevExpress.XtraLayout.Utils.Padding(4, 4, 2, 2);
            this.ItemForAddress2.Size = new System.Drawing.Size(724, 30);
            this.ItemForAddress2.Text = "Tên khách hàng";
            this.ItemForAddress2.TextSize = new System.Drawing.Size(113, 19);
            // 
            // txtSdt
            // 
            this.txtSdt.EnterMoveNextControl = true;
            this.txtSdt.Location = new System.Drawing.Point(144, 130);
            this.txtSdt.Margin = new System.Windows.Forms.Padding(4);
            this.txtSdt.Name = "txtSdt";
            this.txtSdt.Size = new System.Drawing.Size(590, 26);
            this.txtSdt.StyleController = this.dataLayout;
            this.txtSdt.TabIndex = 19;
            this.txtSdt.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.text_SDT_KeyPress);
            // 
            // layoutControlItem1
            // 
            this.layoutControlItem1.Control = this.txtSdt;
            this.layoutControlItem1.Location = new System.Drawing.Point(0, 116);
            this.layoutControlItem1.Name = "layoutControlItem1";
            this.layoutControlItem1.Size = new System.Drawing.Size(724, 30);
            this.layoutControlItem1.Text = "Số điện thoại";
            this.layoutControlItem1.TextSize = new System.Drawing.Size(113, 19);
            // 
            // UC_ThemKH
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 19F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.Controls.Add(this.dataLayout);
            this.Controls.Add(this.barDockControlLeft);
            this.Controls.Add(this.barDockControlRight);
            this.Controls.Add(this.barDockControlBottom);
            this.Controls.Add(this.barDockControlTop);
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "UC_ThemKH";
            this.Size = new System.Drawing.Size(750, 614);
            ((System.ComponentModel.ISupportInitialize)(this.dataLayout)).EndInit();
            this.dataLayout.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.barManager)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.actionImages)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtMaKH.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtDiaChi.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTenKH.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Item_MaKH)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForAddress)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Item_DiaChi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTenKH1.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForAddress1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtTenKH2.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ItemForAddress2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtSdt.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayout;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraEditors.TextEdit txtMaKH;
        private DevExpress.XtraEditors.TextEdit txtDiaChi;
        private DevExpress.XtraEditors.TextEdit txtTenKH;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;
        private DevExpress.XtraLayout.LayoutControlItem Item_MaKH;
        private DevExpress.XtraLayout.LayoutControlItem Item_DiaChi;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem1;
        private DevExpress.XtraLayout.LayoutControlItem ItemForAddress;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem2;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem4;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem5;
        private Utils.SvgImageCollection actionImages;
        private XtraBars.BarManager barManager;
        private XtraBars.BarButtonItem btn_Add;
        private XtraBars.BarButtonItem btn_Clear;
        private XtraBars.BarButtonItem btn_Reset;
        private XtraBars.Bar actionsBar;
        private XtraBars.BarDockControl barDockControlTop;
        private XtraBars.BarDockControl barDockControlBottom;
        private XtraBars.BarDockControl barDockControlLeft;
        private XtraBars.BarDockControl barDockControlRight;
        private XtraBars.BarButtonItem btn_Thoat;
        private XtraEditors.TextEdit txtSdt;
        private XtraEditors.TextEdit txtTenKH1;
        private XtraEditors.TextEdit txtTenKH2;
        private XtraLayout.LayoutControlItem layoutControlItem1;
        private XtraLayout.LayoutControlItem ItemForAddress1;
        private XtraLayout.LayoutControlItem ItemForAddress2;
    }
}
