namespace DevExpress.UITemplates.Collection.UserControls {
    partial class UC_NhapNV {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if(disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
			this.components = new System.ComponentModel.Container();
			this.dataLayout = new DevExpress.XtraDataLayout.DataLayoutControl();
			this.text_TenNV = new DevExpress.XtraEditors.TextEdit();
			this.text_DiaChi = new DevExpress.XtraEditors.TextEdit();
			this.text_MaNV = new DevExpress.XtraEditors.TextEdit();
			this.date_NTNS = new DevExpress.XtraEditors.DateEdit();
			this.cb_GioiTinh = new DevExpress.XtraEditors.ComboBoxEdit();
			this.text_SDT = new DevExpress.XtraEditors.TextEdit();
			this.barManager = new DevExpress.XtraBars.BarManager(this.components);
			this.actionsBar = new DevExpress.XtraBars.Bar();
			this.btn_Save = new DevExpress.XtraBars.BarButtonItem();
			this.btn_ClearData = new DevExpress.XtraBars.BarButtonItem();
			this.btn_Reset = new DevExpress.XtraBars.BarButtonItem();
			this.barDockControlTop = new DevExpress.XtraBars.BarDockControl();
			this.barDockControlBottom = new DevExpress.XtraBars.BarDockControl();
			this.barDockControlLeft = new DevExpress.XtraBars.BarDockControl();
			this.barDockControlRight = new DevExpress.XtraBars.BarDockControl();
			this.actionImages = new DevExpress.Utils.SvgImageCollection(this.components);
			this.layoutControlGroup1 = new DevExpress.XtraLayout.LayoutControlGroup();
			this.autoGeneratedGroup0 = new DevExpress.XtraLayout.LayoutControlGroup();
			this.item_TenNV = new DevExpress.XtraLayout.LayoutControlItem();
			this.emptySpaceItem1 = new DevExpress.XtraLayout.EmptySpaceItem();
			this.item_DiaChi = new DevExpress.XtraLayout.LayoutControlItem();
			this.emptySpaceItem2 = new DevExpress.XtraLayout.EmptySpaceItem();
			this.item_NTNS = new DevExpress.XtraLayout.LayoutControlItem();
			this.emptySpaceItem5 = new DevExpress.XtraLayout.EmptySpaceItem();
			this.emptySpaceItem4 = new DevExpress.XtraLayout.EmptySpaceItem();
			this.item_GioiTinh = new DevExpress.XtraLayout.LayoutControlItem();
			this.item_MaNV = new DevExpress.XtraLayout.LayoutControlItem();
			this.item_SDT = new DevExpress.XtraLayout.LayoutControlItem();
			this.item_Ten = new DevExpress.XtraLayout.LayoutControlItem();
			this.cb_ChucVu = new DevExpress.XtraEditors.ComboBoxEdit();
			this.layoutControlItem1 = new DevExpress.XtraLayout.LayoutControlItem();
			this.emptySpaceItem3 = new DevExpress.XtraLayout.EmptySpaceItem();
			this.text_GhiChu = new System.Windows.Forms.TextBox();
			this.layoutControlItem3 = new DevExpress.XtraLayout.LayoutControlItem();
			this.cb_HSL = new DevExpress.XtraEditors.ComboBoxEdit();
			this.layoutControlItem2 = new DevExpress.XtraLayout.LayoutControlItem();
			this.emptySpaceItem9 = new DevExpress.XtraLayout.EmptySpaceItem();
			this.emptySpaceItem7 = new DevExpress.XtraLayout.EmptySpaceItem();
			this.date_NgayLV = new DevExpress.XtraEditors.DateEdit();
			this.layoutControlItem4 = new DevExpress.XtraLayout.LayoutControlItem();
			this.ItemForPhoto = new DevExpress.XtraLayout.LayoutControlItem();
			this.pt_Anh = new DevExpress.XtraEditors.PictureEdit();
			((System.ComponentModel.ISupportInitialize)(this.dataLayout)).BeginInit();
			this.dataLayout.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.text_TenNV.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.text_DiaChi.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.text_MaNV.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.date_NTNS.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.date_NTNS.Properties.CalendarTimeProperties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.cb_GioiTinh.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.text_SDT.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.barManager)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.actionImages)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.item_TenNV)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.item_DiaChi)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.item_NTNS)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.item_GioiTinh)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.item_MaNV)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.item_SDT)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.item_Ten)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.cb_ChucVu.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.cb_HSL.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem9)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem7)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.date_NgayLV.Properties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.date_NgayLV.Properties.CalendarTimeProperties)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.ItemForPhoto)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.pt_Anh.Properties)).BeginInit();
			this.SuspendLayout();
			// 
			// dataLayout
			// 
			this.dataLayout.AllowCustomization = false;
			this.dataLayout.AllowGeneratingCollectionProperties = DevExpress.Utils.DefaultBoolean.True;
			this.dataLayout.AllowGeneratingNestedGroups = DevExpress.Utils.DefaultBoolean.True;
			this.dataLayout.Controls.Add(this.text_GhiChu);
			this.dataLayout.Controls.Add(this.text_TenNV);
			this.dataLayout.Controls.Add(this.pt_Anh);
			this.dataLayout.Controls.Add(this.text_DiaChi);
			this.dataLayout.Controls.Add(this.text_MaNV);
			this.dataLayout.Controls.Add(this.date_NTNS);
			this.dataLayout.Controls.Add(this.cb_GioiTinh);
			this.dataLayout.Controls.Add(this.text_SDT);
			this.dataLayout.Controls.Add(this.cb_ChucVu);
			this.dataLayout.Controls.Add(this.cb_HSL);
			this.dataLayout.Controls.Add(this.date_NgayLV);
			this.dataLayout.Dock = System.Windows.Forms.DockStyle.Fill;
			this.dataLayout.Location = new System.Drawing.Point(0, 30);
			this.dataLayout.Margin = new System.Windows.Forms.Padding(4);
			this.dataLayout.Name = "dataLayout";
			this.dataLayout.OptionsView.UseParentAutoScaleFactor = true;
			this.dataLayout.Root = this.layoutControlGroup1;
			this.dataLayout.Size = new System.Drawing.Size(583, 487);
			this.dataLayout.TabIndex = 0;
			// 
			// text_TenNV
			// 
			this.text_TenNV.EnterMoveNextControl = true;
			this.text_TenNV.Location = new System.Drawing.Point(105, 38);
			this.text_TenNV.Margin = new System.Windows.Forms.Padding(4);
			this.text_TenNV.Name = "text_TenNV";
			this.text_TenNV.Properties.ValidateOnEnterKey = true;
			this.text_TenNV.Size = new System.Drawing.Size(280, 22);
			this.text_TenNV.StyleController = this.dataLayout;
			this.text_TenNV.TabIndex = 8;
			this.text_TenNV.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.text_TenNV_KeyPress);
			// 
			// text_DiaChi
			// 
			this.text_DiaChi.EnterMoveNextControl = true;
			this.text_DiaChi.Location = new System.Drawing.Point(105, 115);
			this.text_DiaChi.Margin = new System.Windows.Forms.Padding(4);
			this.text_DiaChi.Name = "text_DiaChi";
			this.text_DiaChi.Size = new System.Drawing.Size(466, 22);
			this.text_DiaChi.StyleController = this.dataLayout;
			this.text_DiaChi.TabIndex = 19;
			// 
			// text_MaNV
			// 
			this.text_MaNV.Location = new System.Drawing.Point(105, 12);
			this.text_MaNV.Margin = new System.Windows.Forms.Padding(4);
			this.text_MaNV.Name = "text_MaNV";
			this.text_MaNV.Properties.ReadOnly = true;
			this.text_MaNV.Size = new System.Drawing.Size(280, 22);
			this.text_MaNV.StyleController = this.dataLayout;
			this.text_MaNV.TabIndex = 23;
			// 
			// date_NTNS
			// 
			this.date_NTNS.EditValue = null;
			this.date_NTNS.EnterMoveNextControl = true;
			this.date_NTNS.Location = new System.Drawing.Point(105, 64);
			this.date_NTNS.Margin = new System.Windows.Forms.Padding(4);
			this.date_NTNS.Name = "date_NTNS";
			this.date_NTNS.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
			this.date_NTNS.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.date_NTNS.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.date_NTNS.Size = new System.Drawing.Size(99, 22);
			this.date_NTNS.StyleController = this.dataLayout;
			this.date_NTNS.TabIndex = 16;
			// 
			// cb_GioiTinh
			// 
			this.cb_GioiTinh.Location = new System.Drawing.Point(283, 64);
			this.cb_GioiTinh.Margin = new System.Windows.Forms.Padding(4);
			this.cb_GioiTinh.Name = "cb_GioiTinh";
			this.cb_GioiTinh.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cb_GioiTinh.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
			this.cb_GioiTinh.Size = new System.Drawing.Size(102, 22);
			this.cb_GioiTinh.StyleController = this.dataLayout;
			this.cb_GioiTinh.TabIndex = 6;
			// 
			// text_SDT
			// 
			this.text_SDT.Location = new System.Drawing.Point(105, 166);
			this.text_SDT.MenuManager = this.barManager;
			this.text_SDT.Name = "text_SDT";
			this.text_SDT.Size = new System.Drawing.Size(182, 22);
			this.text_SDT.StyleController = this.dataLayout;
			this.text_SDT.TabIndex = 24;
			this.text_SDT.TextChanged += new System.EventHandler(this.text_SDT_TextChanged);
			this.text_SDT.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.text_SDT_KeyPress);
			// 
			// barManager
			// 
			this.barManager.Bars.AddRange(new DevExpress.XtraBars.Bar[] {
            this.actionsBar});
			this.barManager.DockControls.Add(this.barDockControlTop);
			this.barManager.DockControls.Add(this.barDockControlBottom);
			this.barManager.DockControls.Add(this.barDockControlLeft);
			this.barManager.DockControls.Add(this.barDockControlRight);
			this.barManager.Form = this;
			this.barManager.Images = this.actionImages;
			this.barManager.Items.AddRange(new DevExpress.XtraBars.BarItem[] {
            this.btn_Save,
            this.btn_ClearData,
            this.btn_Reset});
			this.barManager.MainMenu = this.actionsBar;
			this.barManager.MaxItemId = 3;
			// 
			// actionsBar
			// 
			this.actionsBar.BarName = "Actions";
			this.actionsBar.DockCol = 0;
			this.actionsBar.DockRow = 0;
			this.actionsBar.DockStyle = DevExpress.XtraBars.BarDockStyle.Top;
			this.actionsBar.LinksPersistInfo.AddRange(new DevExpress.XtraBars.LinkPersistInfo[] {
            new DevExpress.XtraBars.LinkPersistInfo(this.btn_Save),
            new DevExpress.XtraBars.LinkPersistInfo(this.btn_ClearData),
            new DevExpress.XtraBars.LinkPersistInfo(this.btn_Reset)});
			this.actionsBar.OptionsBar.AllowQuickCustomization = false;
			this.actionsBar.OptionsBar.DisableCustomization = true;
			this.actionsBar.OptionsBar.DrawDragBorder = false;
			this.actionsBar.OptionsBar.MultiLine = true;
			this.actionsBar.OptionsBar.UseWholeRow = true;
			this.actionsBar.Text = "Actions";
			// 
			// btn_Save
			// 
			this.btn_Save.Caption = "Save Changes";
			this.btn_Save.Id = 0;
			this.btn_Save.ImageOptions.ImageIndex = 0;
			this.btn_Save.Name = "btn_Save";
			this.btn_Save.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph;
			this.btn_Save.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btn_Save_ItemClick);
			// 
			// btn_ClearData
			// 
			this.btn_ClearData.Caption = "Clear All";
			this.btn_ClearData.Id = 1;
			this.btn_ClearData.ImageOptions.ImageIndex = 2;
			this.btn_ClearData.Name = "btn_ClearData";
			this.btn_ClearData.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph;
			this.btn_ClearData.ItemClick += new DevExpress.XtraBars.ItemClickEventHandler(this.btn_ClearData_ItemClick);
			// 
			// btn_Reset
			// 
			this.btn_Reset.Caption = "Reset Changes";
			this.btn_Reset.Id = 2;
			this.btn_Reset.ImageOptions.ImageIndex = 1;
			this.btn_Reset.Name = "btn_Reset";
			this.btn_Reset.PaintStyle = DevExpress.XtraBars.BarItemPaintStyle.CaptionGlyph;
			// 
			// barDockControlTop
			// 
			this.barDockControlTop.CausesValidation = false;
			this.barDockControlTop.Dock = System.Windows.Forms.DockStyle.Top;
			this.barDockControlTop.Location = new System.Drawing.Point(0, 0);
			this.barDockControlTop.Manager = this.barManager;
			this.barDockControlTop.Margin = new System.Windows.Forms.Padding(4);
			this.barDockControlTop.Size = new System.Drawing.Size(583, 30);
			// 
			// barDockControlBottom
			// 
			this.barDockControlBottom.CausesValidation = false;
			this.barDockControlBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
			this.barDockControlBottom.Location = new System.Drawing.Point(0, 517);
			this.barDockControlBottom.Manager = this.barManager;
			this.barDockControlBottom.Margin = new System.Windows.Forms.Padding(4);
			this.barDockControlBottom.Size = new System.Drawing.Size(583, 0);
			// 
			// barDockControlLeft
			// 
			this.barDockControlLeft.CausesValidation = false;
			this.barDockControlLeft.Dock = System.Windows.Forms.DockStyle.Left;
			this.barDockControlLeft.Location = new System.Drawing.Point(0, 30);
			this.barDockControlLeft.Manager = this.barManager;
			this.barDockControlLeft.Margin = new System.Windows.Forms.Padding(4);
			this.barDockControlLeft.Size = new System.Drawing.Size(0, 487);
			// 
			// barDockControlRight
			// 
			this.barDockControlRight.CausesValidation = false;
			this.barDockControlRight.Dock = System.Windows.Forms.DockStyle.Right;
			this.barDockControlRight.Location = new System.Drawing.Point(583, 30);
			this.barDockControlRight.Manager = this.barManager;
			this.barDockControlRight.Margin = new System.Windows.Forms.Padding(4);
			this.barDockControlRight.Size = new System.Drawing.Size(0, 487);
			// 
			// actionImages
			// 
			this.actionImages.Add("save", "image://svgimages/save/save.svg");
			this.actionImages.Add("refresh", "image://svgimages/icon builder/actions_refresh.svg");
			this.actionImages.Add("clearall", "image://svgimages/spreadsheet/clearall.svg");
			// 
			// layoutControlGroup1
			// 
			this.layoutControlGroup1.EnableIndentsWithoutBorders = DevExpress.Utils.DefaultBoolean.True;
			this.layoutControlGroup1.GroupBordersVisible = false;
			this.layoutControlGroup1.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.autoGeneratedGroup0});
			this.layoutControlGroup1.Name = "Root";
			this.layoutControlGroup1.Size = new System.Drawing.Size(583, 487);
			this.layoutControlGroup1.TextVisible = false;
			// 
			// autoGeneratedGroup0
			// 
			this.autoGeneratedGroup0.AllowDrawBackground = false;
			this.autoGeneratedGroup0.CustomizationFormText = "autoGeneratedGroup0";
			this.autoGeneratedGroup0.GroupBordersVisible = false;
			this.autoGeneratedGroup0.Items.AddRange(new DevExpress.XtraLayout.BaseLayoutItem[] {
            this.item_TenNV,
            this.ItemForPhoto,
            this.emptySpaceItem1,
            this.item_DiaChi,
            this.emptySpaceItem2,
            this.item_NTNS,
            this.emptySpaceItem5,
            this.item_GioiTinh,
            this.item_MaNV,
            this.item_SDT,
            this.layoutControlItem1,
            this.emptySpaceItem3,
            this.layoutControlItem2,
            this.emptySpaceItem7,
            this.layoutControlItem3,
            this.emptySpaceItem9,
            this.layoutControlItem4,
            this.emptySpaceItem4});
			this.autoGeneratedGroup0.Location = new System.Drawing.Point(0, 0);
			this.autoGeneratedGroup0.Name = "autoGeneratedGroup0";
			this.autoGeneratedGroup0.Size = new System.Drawing.Size(563, 467);
			// 
			// item_TenNV
			// 
			this.item_TenNV.Control = this.text_TenNV;
			this.item_TenNV.CustomizationFormText = "First Name";
			this.item_TenNV.Location = new System.Drawing.Point(0, 26);
			this.item_TenNV.Name = "item_TenNV";
			this.item_TenNV.Size = new System.Drawing.Size(377, 26);
			this.item_TenNV.Text = "Tên";
			this.item_TenNV.TextSize = new System.Drawing.Size(81, 16);
			// 
			// emptySpaceItem1
			// 
			this.emptySpaceItem1.AllowHotTrack = false;
			this.emptySpaceItem1.CustomizationFormText = "emptySpaceItem1";
			this.emptySpaceItem1.Location = new System.Drawing.Point(0, 78);
			this.emptySpaceItem1.MaxSize = new System.Drawing.Size(0, 25);
			this.emptySpaceItem1.MinSize = new System.Drawing.Size(12, 25);
			this.emptySpaceItem1.Name = "emptySpaceItem1";
			this.emptySpaceItem1.Size = new System.Drawing.Size(563, 25);
			this.emptySpaceItem1.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.emptySpaceItem1.TextSize = new System.Drawing.Size(0, 0);
			// 
			// item_DiaChi
			// 
			this.item_DiaChi.Control = this.text_DiaChi;
			this.item_DiaChi.CustomizationFormText = "Address";
			this.item_DiaChi.Location = new System.Drawing.Point(0, 103);
			this.item_DiaChi.Name = "item_DiaChi";
			this.item_DiaChi.Size = new System.Drawing.Size(563, 26);
			this.item_DiaChi.Text = "Địa Chỉ";
			this.item_DiaChi.TextSize = new System.Drawing.Size(81, 16);
			// 
			// emptySpaceItem2
			// 
			this.emptySpaceItem2.AllowHotTrack = false;
			this.emptySpaceItem2.CustomizationFormText = "emptySpaceItem2";
			this.emptySpaceItem2.Location = new System.Drawing.Point(0, 129);
			this.emptySpaceItem2.MaxSize = new System.Drawing.Size(0, 25);
			this.emptySpaceItem2.MinSize = new System.Drawing.Size(12, 25);
			this.emptySpaceItem2.Name = "emptySpaceItem2";
			this.emptySpaceItem2.Size = new System.Drawing.Size(563, 25);
			this.emptySpaceItem2.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.emptySpaceItem2.TextSize = new System.Drawing.Size(0, 0);
			// 
			// item_NTNS
			// 
			this.item_NTNS.Control = this.date_NTNS;
			this.item_NTNS.CustomizationFormText = "Birth Date";
			this.item_NTNS.Location = new System.Drawing.Point(0, 52);
			this.item_NTNS.Name = "item_NTNS";
			this.item_NTNS.Size = new System.Drawing.Size(196, 26);
			this.item_NTNS.Text = "NTNS";
			this.item_NTNS.TextSize = new System.Drawing.Size(81, 16);
			// 
			// emptySpaceItem5
			// 
			this.emptySpaceItem5.AllowHotTrack = false;
			this.emptySpaceItem5.CustomizationFormText = "emptySpaceItem5";
			this.emptySpaceItem5.Location = new System.Drawing.Point(0, 180);
			this.emptySpaceItem5.MaxSize = new System.Drawing.Size(0, 25);
			this.emptySpaceItem5.MinSize = new System.Drawing.Size(12, 25);
			this.emptySpaceItem5.Name = "emptySpaceItem5";
			this.emptySpaceItem5.Size = new System.Drawing.Size(563, 25);
			this.emptySpaceItem5.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.emptySpaceItem5.TextSize = new System.Drawing.Size(0, 0);
			// 
			// emptySpaceItem4
			// 
			this.emptySpaceItem4.AccessibleRole = System.Windows.Forms.AccessibleRole.WhiteSpace;
			this.emptySpaceItem4.AllowHotTrack = false;
			this.emptySpaceItem4.CustomizationFormText = "emptySpaceItem4";
			this.emptySpaceItem4.Location = new System.Drawing.Point(279, 154);
			this.emptySpaceItem4.MaxSize = new System.Drawing.Size(18, 0);
			this.emptySpaceItem4.MinSize = new System.Drawing.Size(18, 10);
			this.emptySpaceItem4.Name = "emptySpaceItem4";
			this.emptySpaceItem4.Size = new System.Drawing.Size(18, 26);
			this.emptySpaceItem4.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.emptySpaceItem4.TextSize = new System.Drawing.Size(0, 0);
			// 
			// item_GioiTinh
			// 
			this.item_GioiTinh.Control = this.cb_GioiTinh;
			this.item_GioiTinh.CustomizationFormText = "Status";
			this.item_GioiTinh.Location = new System.Drawing.Point(196, 52);
			this.item_GioiTinh.Name = "item_GioiTinh";
			this.item_GioiTinh.Padding = new DevExpress.XtraLayout.Utils.Padding(23, 2, 2, 2);
			this.item_GioiTinh.Size = new System.Drawing.Size(181, 26);
			this.item_GioiTinh.Text = "Giới Tính";
			this.item_GioiTinh.TextAlignMode = DevExpress.XtraLayout.TextAlignModeItem.CustomSize;
			this.item_GioiTinh.TextSize = new System.Drawing.Size(49, 16);
			this.item_GioiTinh.TextToControlDistance = 5;
			// 
			// item_MaNV
			// 
			this.item_MaNV.Control = this.text_MaNV;
			this.item_MaNV.CustomizationFormText = "Full Name";
			this.item_MaNV.Location = new System.Drawing.Point(0, 0);
			this.item_MaNV.Name = "item_MaNV";
			this.item_MaNV.Size = new System.Drawing.Size(377, 26);
			this.item_MaNV.Text = "Mã Nhân Viên";
			this.item_MaNV.TextSize = new System.Drawing.Size(81, 16);
			// 
			// item_SDT
			// 
			this.item_SDT.Control = this.text_SDT;
			this.item_SDT.Location = new System.Drawing.Point(0, 154);
			this.item_SDT.Name = "item_SDT";
			this.item_SDT.Size = new System.Drawing.Size(279, 26);
			this.item_SDT.Text = "Số Điện Thoại";
			this.item_SDT.TextSize = new System.Drawing.Size(81, 16);
			this.item_SDT.TextChanged += new System.EventHandler(this.text_SDT_TextChanged);
			// 
			// item_Ten
			// 
			this.item_Ten.Control = this.text_TenNV;
			this.item_Ten.CustomizationFormText = "First Name";
			this.item_Ten.Location = new System.Drawing.Point(0, 26);
			this.item_Ten.Name = "item_Tên";
			this.item_Ten.Size = new System.Drawing.Size(375, 26);
			this.item_Ten.Text = "Tên";
			this.item_Ten.TextSize = new System.Drawing.Size(79, 16);
			// 
			// cb_ChucVu
			// 
			this.cb_ChucVu.Location = new System.Drawing.Point(105, 217);
			this.cb_ChucVu.MenuManager = this.barManager;
			this.cb_ChucVu.Name = "cb_ChucVu";
			this.cb_ChucVu.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cb_ChucVu.Size = new System.Drawing.Size(182, 22);
			this.cb_ChucVu.StyleController = this.dataLayout;
			this.cb_ChucVu.TabIndex = 27;
			// 
			// layoutControlItem1
			// 
			this.layoutControlItem1.Control = this.cb_ChucVu;
			this.layoutControlItem1.Location = new System.Drawing.Point(0, 205);
			this.layoutControlItem1.Name = "layoutControlItem1";
			this.layoutControlItem1.Size = new System.Drawing.Size(279, 26);
			this.layoutControlItem1.Text = "Chức Vụ";
			this.layoutControlItem1.TextSize = new System.Drawing.Size(81, 16);
			// 
			// emptySpaceItem3
			// 
			this.emptySpaceItem3.AllowHotTrack = false;
			this.emptySpaceItem3.Location = new System.Drawing.Point(279, 205);
			this.emptySpaceItem3.Name = "emptySpaceItem3";
			this.emptySpaceItem3.Size = new System.Drawing.Size(19, 26);
			this.emptySpaceItem3.TextSize = new System.Drawing.Size(0, 0);
			// 
			// text_GhiChu
			// 
			this.text_GhiChu.Location = new System.Drawing.Point(105, 270);
			this.text_GhiChu.Multiline = true;
			this.text_GhiChu.Name = "text_GhiChu";
			this.text_GhiChu.Size = new System.Drawing.Size(466, 152);
			this.text_GhiChu.TabIndex = 28;
			// 
			// layoutControlItem3
			// 
			this.layoutControlItem3.Control = this.text_GhiChu;
			this.layoutControlItem3.Location = new System.Drawing.Point(0, 258);
			this.layoutControlItem3.Name = "layoutControlItem3";
			this.layoutControlItem3.Size = new System.Drawing.Size(563, 156);
			this.layoutControlItem3.Text = "Ghi Chú";
			this.layoutControlItem3.TextSize = new System.Drawing.Size(81, 16);
			// 
			// cb_HSL
			// 
			this.cb_HSL.Location = new System.Drawing.Point(403, 217);
			this.cb_HSL.MenuManager = this.barManager;
			this.cb_HSL.Name = "cb_HSL";
			this.cb_HSL.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.cb_HSL.Size = new System.Drawing.Size(168, 22);
			this.cb_HSL.StyleController = this.dataLayout;
			this.cb_HSL.TabIndex = 29;
			// 
			// layoutControlItem2
			// 
			this.layoutControlItem2.Control = this.cb_HSL;
			this.layoutControlItem2.Location = new System.Drawing.Point(298, 205);
			this.layoutControlItem2.Name = "layoutControlItem2";
			this.layoutControlItem2.Size = new System.Drawing.Size(265, 26);
			this.layoutControlItem2.Text = "HSL";
			this.layoutControlItem2.TextSize = new System.Drawing.Size(81, 16);
			// 
			// emptySpaceItem9
			// 
			this.emptySpaceItem9.AllowHotTrack = false;
			this.emptySpaceItem9.Location = new System.Drawing.Point(0, 231);
			this.emptySpaceItem9.MaxSize = new System.Drawing.Size(0, 27);
			this.emptySpaceItem9.MinSize = new System.Drawing.Size(10, 27);
			this.emptySpaceItem9.Name = "emptySpaceItem9";
			this.emptySpaceItem9.Size = new System.Drawing.Size(563, 27);
			this.emptySpaceItem9.SizeConstraintsType = DevExpress.XtraLayout.SizeConstraintsType.Custom;
			this.emptySpaceItem9.TextSize = new System.Drawing.Size(0, 0);
			// 
			// emptySpaceItem7
			// 
			this.emptySpaceItem7.AllowHotTrack = false;
			this.emptySpaceItem7.Location = new System.Drawing.Point(0, 414);
			this.emptySpaceItem7.Name = "emptySpaceItem7";
			this.emptySpaceItem7.Size = new System.Drawing.Size(563, 53);
			this.emptySpaceItem7.TextSize = new System.Drawing.Size(0, 0);
			// 
			// date_NgayLV
			// 
			this.date_NgayLV.EditValue = null;
			this.date_NgayLV.Location = new System.Drawing.Point(402, 166);
			this.date_NgayLV.MenuManager = this.barManager;
			this.date_NgayLV.Name = "date_NgayLV";
			this.date_NgayLV.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.date_NgayLV.Properties.CalendarTimeProperties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
			this.date_NgayLV.Size = new System.Drawing.Size(169, 22);
			this.date_NgayLV.StyleController = this.dataLayout;
			this.date_NgayLV.TabIndex = 30;
			// 
			// layoutControlItem4
			// 
			this.layoutControlItem4.Control = this.date_NgayLV;
			this.layoutControlItem4.Location = new System.Drawing.Point(297, 154);
			this.layoutControlItem4.Name = "layoutControlItem4";
			this.layoutControlItem4.Size = new System.Drawing.Size(266, 26);
			this.layoutControlItem4.Text = "Ngày LV";
			this.layoutControlItem4.TextSize = new System.Drawing.Size(81, 16);
			// 
			// ItemForPhoto
			// 
			this.ItemForPhoto.Control = this.pt_Anh;
			this.ItemForPhoto.CustomizationFormText = "Photo";
			this.ItemForPhoto.Location = new System.Drawing.Point(377, 0);
			this.ItemForPhoto.Name = "ItemForPhoto";
			this.ItemForPhoto.Padding = new DevExpress.XtraLayout.Utils.Padding(23, 2, 2, 2);
			this.ItemForPhoto.Size = new System.Drawing.Size(186, 78);
			this.ItemForPhoto.Text = "Photo:";
			this.ItemForPhoto.TextSize = new System.Drawing.Size(0, 0);
			this.ItemForPhoto.TextVisible = false;
			// 
			// pt_Anh
			// 
			this.pt_Anh.Cursor = System.Windows.Forms.Cursors.Default;
			this.pt_Anh.Location = new System.Drawing.Point(410, 12);
			this.pt_Anh.Margin = new System.Windows.Forms.Padding(4);
			this.pt_Anh.Name = "pt_Anh";
			this.pt_Anh.Properties.PictureStoreMode = DevExpress.XtraEditors.Controls.PictureStoreMode.ByteArray;
			this.pt_Anh.Properties.SizeMode = DevExpress.XtraEditors.Controls.PictureSizeMode.Zoom;
			this.pt_Anh.Size = new System.Drawing.Size(161, 74);
			this.pt_Anh.StyleController = this.dataLayout;
			this.pt_Anh.TabIndex = 17;
			// 
			// UC_NhapNV
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 16F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
			this.Controls.Add(this.dataLayout);
			this.Controls.Add(this.barDockControlLeft);
			this.Controls.Add(this.barDockControlRight);
			this.Controls.Add(this.barDockControlBottom);
			this.Controls.Add(this.barDockControlTop);
			this.Margin = new System.Windows.Forms.Padding(4);
			this.Name = "UC_NhapNV";
			this.Size = new System.Drawing.Size(583, 517);
			((System.ComponentModel.ISupportInitialize)(this.dataLayout)).EndInit();
			this.dataLayout.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.text_TenNV.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.text_DiaChi.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.text_MaNV.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.date_NTNS.Properties.CalendarTimeProperties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.date_NTNS.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.cb_GioiTinh.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.text_SDT.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.barManager)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.actionImages)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlGroup1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.autoGeneratedGroup0)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.item_TenNV)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.item_DiaChi)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.item_NTNS)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.item_GioiTinh)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.item_MaNV)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.item_SDT)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.item_Ten)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.cb_ChucVu.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.cb_HSL.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem9)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.emptySpaceItem7)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.date_NgayLV.Properties.CalendarTimeProperties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.date_NgayLV.Properties)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.layoutControlItem4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.ItemForPhoto)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.pt_Anh.Properties)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

        }

        #endregion

        private DevExpress.XtraDataLayout.DataLayoutControl dataLayout;
        private DevExpress.XtraLayout.LayoutControlGroup layoutControlGroup1;
        private DevExpress.XtraEditors.TextEdit text_DiaChi;
        private DevExpress.XtraEditors.TextEdit text_MaNV;
        private DevExpress.XtraEditors.DateEdit date_NTNS;
        private DevExpress.XtraLayout.LayoutControlGroup autoGeneratedGroup0;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem1;
        private DevExpress.XtraLayout.LayoutControlItem item_DiaChi;
        private DevExpress.XtraLayout.EmptySpaceItem emptySpaceItem2;
        private DevExpress.XtraLayout.LayoutControlItem item_MaNV;
        private DevExpress.XtraLayout.LayoutControlItem item_NTNS;
        private DevExpress.XtraLayout.LayoutControlItem item_GioiTinh;
        private Utils.SvgImageCollection actionImages;
        private XtraBars.BarManager barManager;
        private XtraBars.BarButtonItem btn_Save;
        private XtraBars.BarButtonItem btn_ClearData;
        private XtraBars.BarButtonItem btn_Reset;
        private XtraBars.Bar actionsBar;
        private XtraBars.BarDockControl barDockControlTop;
        private XtraBars.BarDockControl barDockControlBottom;
        private XtraBars.BarDockControl barDockControlLeft;
        private XtraBars.BarDockControl barDockControlRight;
        private XtraEditors.TextEdit text_TenNV;
        private XtraLayout.LayoutControlItem item_TenNV;
        private XtraLayout.EmptySpaceItem emptySpaceItem5;
        private XtraLayout.EmptySpaceItem emptySpaceItem4;
        private XtraLayout.LayoutControlItem item_Ten;
        private XtraEditors.ComboBoxEdit cb_GioiTinh;
		private XtraEditors.TextEdit text_SDT;
		private XtraLayout.LayoutControlItem item_SDT;
		private XtraEditors.ComboBoxEdit cb_ChucVu;
		private XtraLayout.LayoutControlItem layoutControlItem1;
		private XtraLayout.EmptySpaceItem emptySpaceItem3;
		private System.Windows.Forms.TextBox text_GhiChu;
		private XtraLayout.LayoutControlItem layoutControlItem3;
		private XtraEditors.ComboBoxEdit cb_HSL;
		private XtraLayout.LayoutControlItem layoutControlItem2;
		private XtraLayout.EmptySpaceItem emptySpaceItem9;
		private XtraLayout.EmptySpaceItem emptySpaceItem7;
		private XtraEditors.DateEdit date_NgayLV;
		private XtraLayout.LayoutControlItem layoutControlItem4;
		private XtraEditors.PictureEdit pt_Anh;
		private XtraLayout.LayoutControlItem ItemForPhoto;
	}
}
